apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-stages
spec:
  subscriptions:
    repos:
      images:
        - repoURL: nginx
          semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/baloise-incubator/kargo-demo-kustomize.git
        writeBranch: stage/test
        kustomize:
          images:
            - image: nginx
              path: stages/test
    argoCDAppUpdates:
      - appName: kargo-demo-test
        appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-stages
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/baloise-incubator/kargo-demo-kustomize.git
        writeBranch: stage/uat
        kustomize:
          images:
            - image: nginx
              path: stages/uat
    argoCDAppUpdates:
      - appName: kargo-demo-uat
        appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-stages
spec:
  subscriptions:
    upstreamStages:
      - name: uat
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/baloise-incubator/kargo-demo-kustomize.git
        writeBranch: stage/prod
        kustomize:
          images:
            - image: nginx
              path: stages/prod
    argoCDAppUpdates:
      - appName: kargo-demo-prod
        appNamespace: argocd
