apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-demo-stages
  namespace: kargo-demo-stages
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /github/token
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /github/username
      secretKey: username
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    creationPolicy: Merge
    deletionPolicy: Delete
---
kind: Secret
apiVersion: v1
metadata:
  name: kargo-demo-stages
  namespace: kargo-demo-stages
  labels:
    kargo.akuity.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/baloise-incubator/kargo-demo-kustomize.git"
type: Opaque