apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-stages
spec:
  subscriptions:
    - image:
        repoURL: nginx
        semverConstraint: ^1.24.0
    - git:
        repoURL: https://github.com/baloise-incubator/kargo-demo-kustomize.git
        branch: master

